Tejasya/Tejasya/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tejasya.Areas.Admin.Controllers
{
    [Area("admin")]
    //[Route("admin/[controller]/[Action]")]
    [Route("admin")]

    public class HomeController : Controller
    {
        // GET: HomeController
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: HomeController/Details/5
        [Route("details/{id}")]

        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Tejasya/Tejasya/Areas/Financial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tejasya.Areas.Financial.Controllers
{
    [Area("financial")] 
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Tejasya/Tejasya/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tejasya.Repository;

namespace Tejasya.Components
{
    public class TopBooksViewComponent:ViewComponent
    {
        //public BookController(BookRepository bookRepository,
        //    LanguageRepository languageRepository,
        //    IWebHostEnvironment webHostEnvironment)
        //{
        //    _bookRepository = bookRepository;
        //    _languageRepository = languageRepository;
        //    _webHostEnvironment = webHostEnvironment;

        //}

        private  readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }


        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

Tejasya/Tejasya/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using Tejasya.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Tejasya.Repository;
using Tejasya.Service;
using Microsoft.AspNetCore.Authorization;

namespace Tejasya.Controllers
{
    public class HomeController : Controller
    {
        private readonly NewBookAlertConfig _newBookAlertConfiguration;
        private readonly NewBookAlertConfig _thirdPartyBookConfiguration;
        private readonly IMessageRepository _messageRepository;
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        public HomeController(IOptionsSnapshot<NewBookAlertConfig> newBookAlertConfiguration,
            IMessageRepository messageRepository,
            IUserService userService,
            IEmailService emailService) /* type ctor and click tab twice*/
        {
            _newBookAlertConfiguration = newBookAlertConfiguration.Get("InternalBook");
            _thirdPartyBookConfiguration = newBookAlertConfiguration.Get("ThirdPartyBook");
            _messageRepository = messageRepository;
            _userService = userService;
            _emailService = emailService;
        }



        [ViewData]
        public string CustomProperty { get; set; }
        [ViewData]
        public string Title { get; set; }
        [ViewData]
        public BookModel Book { get; set; }




        public async Task<ViewResult> Index()
        {

           // UserEmailOptions options = new UserEmailOptions
           // {
           //     ToEmails=new List<string>() { "test@gmail.com"},
           //     PlaceHolders= new List<KeyValuePair<string, string>> ()
           //     {
           //         new KeyValuePair<string, string>("{{UserName}}","Tejasya")
           //     }
           // };

           //await _emailService.SendTestEmail(options);




            //ViewBag.Title = "Tejasya";

            //dynamic data = new ExpandoObject();
            //data.id = 1;
            //data.name = "tejasya";

            //ViewBag.data = data;

            ////viewbag is used to transfer data from controller to its view, not other view.
            //ViewBag.type = new BookModel() { Id = 5, Author = "this is author" };





            //ViewData["property1"] = "Nitish Kaushik";


            //ViewData["book"] = new BookModel()
            //{
            //    Author="Sangam",

            ////viewdata is used to transfer data from controller to view simmilar to viewbag but it is slightly differnet from viewbag, as of now i dont know
            //    Id=1
            //};

            //var newBook = configuration.GetSection("NewBookAlert").GetValue<bool>("DisplayNewBookAlert");
            //var result = newBook.GetValue<bool>("DisplayNewBookAlert");
            //var bookName = newBook.GetValue<string>("BookName");

            // var newBookAlert = new NewBookAlertConfig();
            //configuration.Bind("NewBookAlert", newBookAlert);




            var userId = _userService.GetUserId();

            var isLoggedIn = _userService.IsAuthenticated();

            bool isDisplay = _newBookAlertConfiguration.DisplayNewBookAlert;
            bool isDisplay1 = _thirdPartyBookConfiguration.DisplayNewBookAlert;





            // var value = _messageRepository.GetName();




            // bool isDisplay = newBookAlert.DisplayNewBookAlert;


            // var result1 = ConfigurationBinder["DisplayNewBookAlert"];
            //var result = _newBookAlertConfiguration["AppName"];
            //var key1 = _newBookAlertConfiguration["infoObj:key1"];
            //var key2 = _newBookAlertConfiguration["infoObj:key2"];
            //var key3 = _newBookAlertConfiguration["infoObj:key3:key3obj1"];



            //Title = "Home Page from Controller";
            //CustomProperty = "Custom Value";

            //Book = new BookModel() {Id=1, Author="Moomeen" };

            return View();
        }


        // [Route("about-us/")][HttpGet]
        // [Route("about-us/")]
        //  [Route("about-us/",Name ="aboutus")]
        //  [Route("about-us/", Name = "aboutus", Order =1)]

        public ViewResult Aboutus(int id)
        {
            Title = "About us Page from Controller";
            return View();
        }

        //  [HttpGet("contact-us")]
        [Authorize(Roles ="Admin,User")]
        public ViewResult ContactUs()
        {
            Title = "Contact us  Page from Controller";
            return View();
        }

    }
}

Tejasya/Tejasya/Views/Home/Aboutus.cshtml
@*@{
    ViewData["Title"] = "About Us";
}*@

<h1>This is About Us Page.</h1>

Tejasya/Tejasya/Views/Home/ContactUs.cshtml
@*@{
    ViewData["Title"] = "Contact Us";
}*@

<h1>ContactUs</h1>

Tejasya/Tejasya/Views/Home/Index.cshtml
@*@{
        ViewData["Title"] = "Home";
    }*@


@*@{
        dynamic data = ViewBag.Data;
        //the dynamic is used to transfer the data from its contrller  for viewbag
    }*@


@*@{
        var bookInfo = ViewData["book"] as BookModel;
        //here the casting must be done as BookModel

    }*@


@{
    var book = ViewData["Book"] as BookModel;
}


@inject Tejasya.Repository.IBookRepository _bookRepository




<section class="text-center container">
    <div>


        <partial name="_HomeTitle" />

        @*<br /><h1>Id=@book.Id</h1>
        <h1>Id=@book.Author</h1>*@

        <p class="lead text-muted">
            @*@data.Id @data.Name
                <br />
                Id=@ViewBag.Type.Id
                Author=@ViewBag.Type.Author*@


            @*@ViewData["Property1"]*@

            <h1>@ViewData["CustomProperty"]</h1>


            <br />



            @*<environment names="Development">
                    <h3>Development</h3>
                </environment>

                <environment names="Production,staging">
                    <h3>Production</h3>
                </environment>*@
            @*both include and name work as same*@


            <environment include="Development">
                <h3>Development</h3>
            </environment>

            <environment include="Production">
                <h3>Production</h3>
            </environment>


            <environment exclude="Staging">
                <h3>Production</h3>
            </environment>


            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            when an unknown printer took a galley of type and scrambled it to make a type
            specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in
            the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus PageMaker including
            versions of Lorem Ipsum.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Book</a>
        </p>

        @foreach (var item in await _bookRepository.GetAllBooks())
        {
            <h2>@item.Title</h2>
        }

    </div>
</section>
<div class="py-5 bg-light">
    <div class="container">

        <h3 class="h3">Top Books</h3>


        @await Component.InvokeAsync("TopBooks", new { count = 3 })  @*using the view componnets from component.cs and shared folder in component folder with default name*@


        @*<vc:top-books count="3"></vc:top-books>*@   @*this method is also used for rendering view componenet*@

    </div>
</div>


<div>
    <custom-email my-email="mango@gmail.com" class="text-center"></custom-email>

</div>

@section scripts{
    <script>
        $(document).ready(function () {
            // alert("document is ready");
        });
    </script>
}

Tejasya/Tejasya/Views/Home/_HomeTitle.cshtml
<h1>Tejasya from the book</h1>